version: "3.9"

services:
  db:
    image: postgresql:16-alpine3.19
    conreiner_name: db
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 10s
      retries: 5
